name: build
on: [push, pull_request, release]
jobs:
  xocde-build:
    name: Xcode Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build CantoneseIM
      run: set -o pipefail && xcodebuild clean build -project CantoneseIM.xcodeproj -scheme CantoneseIM -configuration Debug -destination "platform=iOS Simulator,name=iPhone 11 Pro Max" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
